### ISSUE TITLE
colored mesh

### ISSUE THREAD

**Issue by hefan14** [BaowenZ/RaDe-GS#36]
Hello, I would like to ask how to extract the colored mesh? I see that you are using o3d.t geometry VoxelBlockGrid method, but it does not integrate color information. I tried using o3d. pipelines. integration ScalableTSDFVolume replaces o3dt.geometry VoxelBlockGrid， but I still can't solve the problem of inconsistent color and depth dimensions. I am looking forward to your advice！

**Comment by BaowenZ** [comment]
Hi! I have updated code for colored mesh extraction.

**Comment by markinruc** [comment]
> Hi! I have updated code for colored mesh extraction.

Hi! I tried the code `mesh_extract_tetrahedra.py`. However, the mesh still does not have the texture. I wonder if only mesh_extract.py can generate texture mesh. Thank you!

**Comment by BaowenZ** [comment]
Hi! Currently, `mesh_extract.py` can output texture while `mesh_extract_tetrahedra.py` only outputs shapes.
